### ISSUE TITLE
Barcode.Create width argument doesn't scale actual barcode

### ISSUE THREAD

**Issue by ghost** [DTGVFN/CSHARP-Barcode#2]
The [`Barcode.Create` method](https://github.com/DTGVFN/CSHARP-Barcode/blob/052384c170f5e27fd0861020374ada88f45d52da/CSHARP-Barcode/Barcode.cs#L21) doesn't actually scale the barcode if the width is changed, it only changes the width of the bitmap which also results in cropping when a small width is entered with large text.

**Comment by DTGVFN** [comment]
Hi,

Thank You For your Code. +1: 
This has been fixed.
